import { Card } from "@/components/ui/card";
import { DashboardStrip } from "@/components/ui/custom/DashboardStrip";
import { SupplierDataTable } from "@/components/ui/custom/SupplierDataList";
import { DataTable } from "@/components/ui/custom/SupplierDataList";

export default function SupplierOrderPage() {



    const data: DataTable[] = [
        {
            "order_id": "ORD7H2K9P4M1N6Q3",
            "supplier_company": "Global Textiles Inc.",
            "importer_company": "ABC Imports LLC",
            "third_party": "TradeLink Solutions",
            "item_name": "Enviro Cotton Fabric",
            "combined_item_name": "Enviro Cotton Fabric",
            "country_of_origin": "India",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 5.25,
            "brands": "PremiumWeave, EcoTextile",
            "no_of_boxes": 120,
            "per_bag_size": 25,
            "total_weight": 3000,
            "total_amount": 15750.00,
            "invoice_1_rate": 1.20,
            "invoice_2_rate": 4.05,
            "total_invoice_1_amount": 3600.00,
            "total_invoice_2_amount": 12150.00,
            "grand_total": 15750.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 15750.00,
            "contract_no": "CT2023-001",
            "contract_date": new Date("2023-01-15"),
            "indenter_broker": "John Smith",
            "clearing_agent": "FastClear Logistics",
            "expected_shipment": new Date("2023-02-10"),
            "destination_port": "Los Angeles",
            "estimated_time_of_arrival": new Date("2023-03-05"),
            "status": "open"
        },
        {
            "order_id": "ORD5T8R2W1Y9U4I7",
            "supplier_company": "Oceanic Seafood Exports",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Marine Trade Partners",
            "combined_item_name": "Frozen Shrimp",
            "country_of_origin": "Vietnam",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 12.75,
            "brands": "BlueSea, OceanFresh",
            "no_of_boxes": 80,
            "per_bag_size": 10,
            "total_weight": 800,
            "total_amount": 10200.00,
            "invoice_1_rate": 3.50,
            "invoice_2_rate": 9.25,
            "total_invoice_1_amount": 2800.00,
            "total_invoice_2_amount": 7400.00,
            "grand_total": 10200.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 10200.00,
            "contract_no": "CT2023-002",
            "contract_date": new Date("2023-01-20"),
            "indenter_broker": "Sarah Johnson",
            "clearing_agent": "PortClear Services",
            "expected_shipment": new Date("2023-02-15"),
            "destination_port": "New York",
            "estimated_time_of_arrival": new Date("2023-03-12"),
            "status": "pending"
        },
        {
            "order_id": "ORD3V6B9N2M8Q1P4",
            "supplier_company": "Alpine Dairy Products",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "FoodTrade International",
            "combined_item_name": "Organic Cheese",
            "country_of_origin": "Switzerland",
            "purchase_currency": "EUR",
            "purchase_rate_per_kg": 8.40,
            "brands": "AlpineGold, MountainFresh",
            "no_of_boxes": 60,
            "per_bag_size": 5,
            "total_weight": 300,
            "total_amount": 2520.00,
            "invoice_1_rate": 2.10,
            "invoice_2_rate": 6.30,
            "total_invoice_1_amount": 630.00,
            "total_invoice_2_amount": 1890.00,
            "grand_total": 2520.00,
            "exchange_rate_invoice_1": 1.1,
            "exchange_rate_invoice_2": 1.1,
            "result_box": 2772.00,
            "contract_no": "CT2023-003",
            "contract_date": new Date("2023-02-05"),
            "indenter_broker": "Michael Brown",
            "clearing_agent": "EuroClear Logistics",
            "expected_shipment": new Date("2023-03-01"),
            "destination_port": "Miami",
            "estimated_time_of_arrival": new Date("2023-03-25"),
            "status": "close"
        },
        {
            "order_id": "ORD9J4K7L2H8G3F1",
            "supplier_company": "Tropical Fruits Ltd.",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "FreshTrade Partners",
            "combined_item_name": "Mango Pulp",
            "country_of_origin": "Thailand",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 3.80,
            "brands": "SunnyHarvest",
            "no_of_boxes": 150,
            "per_bag_size": 20,
            "total_weight": 3000,
            "total_amount": 11400.00,
            "invoice_1_rate": 0.90,
            "invoice_2_rate": 2.90,
            "total_invoice_1_amount": 2700.00,
            "total_invoice_2_amount": 8700.00,
            "grand_total": 11400.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 11400.00,
            "contract_no": "CT2023-004",
            "contract_date": new Date("2023-02-10"),
            "indenter_broker": "David Wilson",
            "clearing_agent": "Tropical Logistics",
            "expected_shipment": new Date("2023-03-05"),
            "destination_port": "Houston",
            "estimated_time_of_arrival": new Date("2023-04-02"),
            "status": "close"
        },
        {
            "order_id": "ORD1X5Z8C2V7B9N3",
            "supplier_company": "Midwest Grain Co.",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "AgriTrade Solutions",
            "combined_item_name": "Organic Wheat",
            "country_of_origin": "USA",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 2.15,
            "brands": "Heartland, GoldenFields",
            "no_of_boxes": 200,
            "per_bag_size": 50,
            "total_weight": 10000,
            "total_amount": 21500.00,
            "invoice_1_rate": 0.50,
            "invoice_2_rate": 1.65,
            "total_invoice_1_amount": 5000.00,
            "total_invoice_2_amount": 16500.00,
            "grand_total": 21500.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 21500.00,
            "contract_no": "CT2023-005",
            "contract_date": new Date("2023-02-15"),
            "indenter_broker": "Robert Taylor",
            "clearing_agent": "AgriClear Services",
            "expected_shipment": new Date("2023-03-12"),
            "destination_port": "Seattle",
            "estimated_time_of_arrival": new Date("2023-04-10"),
            "status": "close"
        },
        {
            "order_id": "ORD6Y9T4R1E8W3Q2",
            "supplier_company": "Scandinavian Timber",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Nordic Trade Partners",
            "combined_item_name": "Pine Wood Planks",
            "country_of_origin": "Sweden",
            "purchase_currency": "EUR",
            "purchase_rate_per_kg": 4.75,
            "brands": "NordicWood",
            "no_of_boxes": 90,
            "per_bag_size": 30,
            "total_weight": 2700,
            "total_amount": 12825.00,
            "invoice_1_rate": 1.25,
            "invoice_2_rate": 3.50,
            "total_invoice_1_amount": 3375.00,
            "total_invoice_2_amount": 9450.00,
            "grand_total": 12825.00,
            "exchange_rate_invoice_1": 1.1,
            "exchange_rate_invoice_2": 1.1,
            "result_box": 14107.50,
            "contract_no": "CT2023-006",
            "contract_date": new Date("2023-02-20"),
            "indenter_broker": "Emma Johnson",
            "clearing_agent": "Nordic Clear",
            "expected_shipment": new Date("2023-03-18"),
            "destination_port": "Baltimore",
            "estimated_time_of_arrival": new Date("2023-04-15"),
            "status": "close"
        },
        {
            "order_id": "ORD2U7I4O1P9K6J8",
            "supplier_company": "Mediterranean Olive Oil",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "EuroFood Traders",
            "combined_item_name": "Extra Virgin Olive Oil",
            "country_of_origin": "Spain",
            "purchase_currency": "EUR",
            "purchase_rate_per_kg": 9.60,
            "brands": "GoldenGrove, Mediterra",
            "no_of_boxes": 70,
            "per_bag_size": 15,
            "total_weight": 1050,
            "total_amount": 10080.00,
            "invoice_1_rate": 2.40,
            "invoice_2_rate": 7.20,
            "total_invoice_1_amount": 2520.00,
            "total_invoice_2_amount": 7560.00,
            "grand_total": 10080.00,
            "exchange_rate_invoice_1": 1.1,
            "exchange_rate_invoice_2": 1.1,
            "result_box": 11088.00,
            "contract_no": "CT2023-007",
            "contract_date": new Date("2023-03-01"),
            "indenter_broker": "Carlos Mendez",
            "clearing_agent": "Mediterranean Logistics",
            "expected_shipment": new Date("2023-03-25"),
            "destination_port": "Savannah",
            "estimated_time_of_arrival": new Date("2023-04-20"),
            "status": "close"
        },
        {
            "order_id": "ORD8F3D5S2A7G9H1",
            "supplier_company": "Himalayan Tea Estate",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Asia Tea Traders",
            "combined_item_name": "Darjeeling Tea",
            "country_of_origin": "India",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 18.50,
            "brands": "MountainMist, GoldenLeaf",
            "no_of_boxes": 50,
            "per_bag_size": 10,
            "total_weight": 500,
            "total_amount": 9250.00,
            "invoice_1_rate": 4.50,
            "invoice_2_rate": 14.00,
            "total_invoice_1_amount": 2250.00,
            "total_invoice_2_amount": 7000.00,
            "grand_total": 9250.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 9250.00,
            "contract_no": "CT2023-008",
            "contract_date": new Date("2023-03-05"),
            "indenter_broker": "Raj Patel",
            "clearing_agent": "Asia Clear Services",
            "expected_shipment": new Date("2023-04-01"),
            "destination_port": "New Orleans",
            "estimated_time_of_arrival": new Date("2023-04-28"),
            "status": "close"
        },
        {
            "order_id": "ORD4Q6W9E2R7T3Y1",
            "supplier_company": "African Coffee Co.",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Global Coffee Partners",
            "combined_item_name": "Arabica Coffee Beans",
            "country_of_origin": "Ethiopia",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 7.80,
            "brands": "Highland, Sunrise",
            "no_of_boxes": 110,
            "per_bag_size": 25,
            "total_weight": 2750,
            "total_amount": 21450.00,
            "invoice_1_rate": 1.80,
            "invoice_2_rate": 6.00,
            "total_invoice_1_amount": 4950.00,
            "total_invoice_2_amount": 16500.00,
            "grand_total": 21450.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 21450.00,
            "contract_no": "CT2023-009",
            "contract_date": new Date("2023-03-10"),
            "indenter_broker": "Thomas Wilson",
            "clearing_agent": "Coffee Trade Logistics",
            "expected_shipment": new Date("2023-04-05"),
            "destination_port": "Charleston",
            "estimated_time_of_arrival": new Date("2023-05-03"),
            "status": "close"
        },
        {
            "order_id": "ORD0P9L8K7J6H5G4",
            "supplier_company": "South American Cocoa",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Chocolate Trade Inc.",
            "combined_item_name": "Cocoa Beans",
            "country_of_origin": "Ecuador",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 6.25,
            "brands": "AmazonGold",
            "no_of_boxes": 85,
            "per_bag_size": 40,
            "total_weight": 3400,
            "total_amount": 21250.00,
            "invoice_1_rate": 1.50,
            "invoice_2_rate": 4.75,
            "total_invoice_1_amount": 5100.00,
            "total_invoice_2_amount": 16150.00,
            "grand_total": 21250.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 21250.00,
            "contract_no": "CT2023-010",
            "contract_date": new Date("2023-03-15"),
            "indenter_broker": "Maria Garcia",
            "clearing_agent": "Cocoa Clear Services",
            "expected_shipment": new Date("2023-04-10"),
            "destination_port": "Jacksonville",
            "estimated_time_of_arrival": new Date("2023-05-08"),
            "status": "close"
        },
        {
            "order_id": "ORD3M2N1B4V6C8X9",
            "supplier_company": "New Zealand Dairy",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Pacific Food Traders",
            "combined_item_name": "Whole Milk Powder",
            "country_of_origin": "New Zealand",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 4.90,
            "brands": "KiwiGold, SouthernStar",
            "no_of_boxes": 130,
            "per_bag_size": 25,
            "total_weight": 3250,
            "total_amount": 15925.00,
            "invoice_1_rate": 1.10,
            "invoice_2_rate": 3.80,
            "total_invoice_1_amount": 3575.00,
            "total_invoice_2_amount": 12350.00,
            "grand_total": 15925.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 15925.00,
            "contract_no": "CT2023-011",
            "contract_date": new Date("2023-03-20"),
            "indenter_broker": "James Wilson",
            "clearing_agent": "Pacific Clear Logistics",
            "expected_shipment": new Date("2023-04-15"),
            "destination_port": "Long Beach",
            "estimated_time_of_arrival": new Date("2023-05-12"),
            "status": "close"
        },
        {
            "order_id": "ORD7Z5X3C1V9B8N2",
            "supplier_company": "Indonesian Spices",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Asia Spice Traders",
            "combined_item_name": "Vanilla Beans",
            "country_of_origin": "Indonesia",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 120.00,
            "brands": "IslandSpice",
            "no_of_boxes": 25,
            "per_bag_size": 2,
            "total_weight": 50,
            "total_amount": 6000.00,
            "invoice_1_rate": 30.00,
            "invoice_2_rate": 90.00,
            "total_invoice_1_amount": 1500.00,
            "total_invoice_2_amount": 4500.00,
            "grand_total": 6000.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 6000.00,
            "contract_no": "CT2023-012",
            "contract_date": new Date("2023-03-25"),
            "indenter_broker": "Lee Wong",
            "clearing_agent": "Island Clear Services",
            "expected_shipment": new Date("2023-04-20"),
            "destination_port": "Oakland",
            "estimated_time_of_arrival": new Date("2023-05-18"),
            "status": "close"
        },
        {
            "order_id": "ORD1K9J7H5G3F8D2",
            "supplier_company": "Canadian Maple Products",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "North American Food Traders",
            "combined_item_name": "Maple Syrup",
            "country_of_origin": "Canada",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 15.75,
            "brands": "NorthernGold, MapleLeaf",
            "no_of_boxes": 65,
            "per_bag_size": 10,
            "total_weight": 650,
            "total_amount": 10237.50,
            "invoice_1_rate": 3.75,
            "invoice_2_rate": 12.00,
            "total_invoice_1_amount": 2437.50,
            "total_invoice_2_amount": 7800.00,
            "grand_total": 10237.50,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 10237.50,
            "contract_no": "CT2023-013",
            "contract_date": new Date("2023-04-01"),
            "indenter_broker": "Robert Johnson",
            "clearing_agent": "NorthClear Logistics",
            "expected_shipment": new Date("2023-04-25"),
            "destination_port": "Norfolk",
            "estimated_time_of_arrival": new Date("2023-05-22"),
            "status": "close"
        },
        {
            "order_id": "ORD5T7R3E1W9Q8U2",
            "supplier_company": "Australian Beef Co.",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Pacific Meat Traders",
            "combined_item_name": "Angus Beef",
            "country_of_origin": "Australia",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 11.25,
            "brands": "OutbackPrime",
            "no_of_boxes": 95,
            "per_bag_size": 15,
            "total_weight": 1425,
            "total_amount": 16031.25,
            "invoice_1_rate": 2.75,
            "invoice_2_rate": 8.50,
            "total_invoice_1_amount": 3918.75,
            "total_invoice_2_amount": 12112.50,
            "grand_total": 16031.25,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 16031.25,
            "contract_no": "CT2023-014",
            "contract_date": new Date("2023-04-05"),
            "indenter_broker": "Sarah Williams",
            "clearing_agent": "MeatClear Services",
            "expected_shipment": new Date("2023-04-30"),
            "destination_port": "Tacoma",
            "estimated_time_of_arrival": new Date("2023-05-26"),
            "status": "close"
        },
        {
            "order_id": "ORD9N8B6V4C2X1Z3",
            "supplier_company": "Chilean Wine Exporters",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Vineyard Trade Partners",
            "combined_item_name": "Cabernet Sauvignon",
            "country_of_origin": "Chile",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 8.40,
            "brands": "AndesValley, PacificVine",
            "no_of_boxes": 75,
            "per_bag_size": 12,
            "total_weight": 900,
            "total_amount": 7560.00,
            "invoice_1_rate": 2.10,
            "invoice_2_rate": 6.30,
            "total_invoice_1_amount": 1890.00,
            "total_invoice_2_amount": 5670.00,
            "grand_total": 7560.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 7560.00,
            "contract_no": "CT2023-015",
            "contract_date": new Date("2023-04-10"),
            "indenter_broker": "Carlos Rodriguez",
            "clearing_agent": "WineClear Logistics",
            "expected_shipment": new Date("2023-05-05"),
            "destination_port": "San Diego",
            "estimated_time_of_arrival": new Date("2023-05-30"),
            "status": "close"
        },
        {
            "order_id": "ORD2F4D6S8A1G3H5",
            "supplier_company": "Japanese Electronics Inc.",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "TechTrade Global",
            "combined_item_name": "Semiconductor Chips",
            "country_of_origin": "Japan",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 850.00,
            "brands": "TechNippon",
            "no_of_boxes": 10,
            "per_bag_size": 5,
            "total_weight": 50,
            "total_amount": 42500.00,
            "invoice_1_rate": 200.00,
            "invoice_2_rate": 650.00,
            "total_invoice_1_amount": 10000.00,
            "total_invoice_2_amount": 32500.00,
            "grand_total": 42500.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 42500.00,
            "contract_no": "CT2023-016",
            "contract_date": new Date("2023-04-15"),
            "indenter_broker": "Kenji Tanaka",
            "clearing_agent": "TechClear Services",
            "expected_shipment": new Date("2023-05-10"),
            "destination_port": "Portland",
            "estimated_time_of_arrival": new Date("2023-06-05"),
            "status": "close"
        },
        {
            "order_id": "ORD6J8K9L7M5N3P1",
            "supplier_company": "Italian Marble Co.",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "EuroStone Traders",
            "combined_item_name": "Carrara Marble Slabs",
            "country_of_origin": "Italy",
            "purchase_currency": "EUR",
            "purchase_rate_per_kg": 6.80,
            "brands": "AlpineStone",
            "no_of_boxes": 40,
            "per_bag_size": 50,
            "total_weight": 2000,
            "total_amount": 13600.00,
            "invoice_1_rate": 1.70,
            "invoice_2_rate": 5.10,
            "total_invoice_1_amount": 3400.00,
            "total_invoice_2_amount": 10200.00,
            "grand_total": 13600.00,
            "exchange_rate_invoice_1": 1.1,
            "exchange_rate_invoice_2": 1.1,
            "result_box": 14960.00,
            "contract_no": "CT2023-017",
            "contract_date": new Date("2023-04-20"),
            "indenter_broker": "Marco Rossi",
            "clearing_agent": "StoneClear Logistics",
            "expected_shipment": new Date("2023-05-15"),
            "destination_port": "Boston",
            "estimated_time_of_arrival": new Date("2023-06-10"),
            "status": "close"
        },
        {
            "order_id": "ORD4Q2W3E5R7T9Y1",
            "supplier_company": "Brazilian Coffee Exporters",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Americas Coffee Traders",
            "combined_item_name": "Santos Coffee Beans",
            "country_of_origin": "Brazil",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 6.50,
            "brands": "BrazilGold, Amazonia",
            "no_of_boxes": 100,
            "per_bag_size": 30,
            "total_weight": 3000,
            "total_amount": 19500.00,
            "invoice_1_rate": 1.50,
            "invoice_2_rate": 5.00,
            "total_invoice_1_amount": 4500.00,
            "total_invoice_2_amount": 15000.00,
            "grand_total": 19500.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 19500.00,
            "contract_no": "CT2023-018",
            "contract_date": new Date("2023-04-25"),
            "indenter_broker": "Pedro Silva",
            "clearing_agent": "CoffeeClear Services",
            "expected_shipment": new Date("2023-05-20"),
            "destination_port": "Philadelphia",
            "estimated_time_of_arrival": new Date("2023-06-15"),
            "status": "close"
        },
        {
            "order_id": "ORD8U7I6O5P4K3J2",
            "supplier_company": "South African Diamonds",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "Gemstone Trade Inc.",
            "combined_item_name": "Uncut Diamonds",
            "country_of_origin": "South Africa",
            "purchase_currency": "USD",
            "purchase_rate_per_kg": 12500.00,
            "brands": "CapeDiamonds",
            "no_of_boxes": 5,
            "per_bag_size": 1,
            "total_weight": 5,
            "total_amount": 62500.00,
            "invoice_1_rate": 3000.00,
            "invoice_2_rate": 9500.00,
            "total_invoice_1_amount": 15000.00,
            "total_invoice_2_amount": 47500.00,
            "grand_total": 62500.00,
            "exchange_rate_invoice_1": 1.0,
            "exchange_rate_invoice_2": 1.0,
            "result_box": 62500.00,
            "contract_no": "CT2023-019",
            "contract_date": new Date("2023-05-01"),
            "indenter_broker": "Thabo Mbeki",
            "clearing_agent": "GemClear Logistics",
            "expected_shipment": new Date("2023-05-25"),
            "destination_port": "Newark",
            "estimated_time_of_arrival": new Date("2023-06-20"),
            "status": "close"
        },
        {
            "order_id": "ORD0M9N8B7V6C5X4",
            "supplier_company": "Turkish Textile Mills",
            "importer_company": "ABC Imports LLC",
            "item_name": "Enviro Cotton Fabric",
            "third_party": "EuroTextile Traders",
            "combined_item_name": "Turkish Towels",
            "country_of_origin": "Turkey",
            "purchase_currency": "EUR",
            "purchase_rate_per_kg": 7.20,
            "brands": "AegeanCotton, Bosphorus",
            "no_of_boxes": 85,
            "per_bag_size": 20,
            "total_weight": 1700,
            "total_amount": 12240.00,
            "invoice_1_rate": 1.80,
            "invoice_2_rate": 5.40,
            "total_invoice_1_amount": 3060.00,
            "total_invoice_2_amount": 9180.00,
            "grand_total": 12240.00,
            "exchange_rate_invoice_1": 1.1,
            "exchange_rate_invoice_2": 1.1,
            "result_box": 13464.00,
            "contract_no": "CT2023-020",
            "contract_date": new Date("2023-05-05"),
            "indenter_broker": "Mehmet Yilmaz",
            "clearing_agent": "TextileClear Services",
            "expected_shipment": new Date("2023-05-30"),
            "destination_port": "San Francisco",
            "estimated_time_of_arrival": new Date("2023-06-25"),
            "status": "pending"
        }
    ]
    return (
        <>
            <DashboardStrip title="Supplier Orders" />
            <Card className="mt-4 px-4 py-[8px]">
                <SupplierDataTable data={data} />
            </Card>
        </>
    )
}